<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>MiniERP2</RootNamespace>
    <AssemblyName>MiniERP2</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests/**" />
    <EmbeddedResource Remove="Tests/**" />
    <None Remove="Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.6.1" />
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.75.0.4210" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.0" />
  </ItemGroup>

</Project>
